services:
  api:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    image: narriva_server:latest
    container_name: narriva_server
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/narriva_server
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - /app/node_modules
      - /app/generated
    depends_on:
      - postgres
    command: sh -c "npx prisma generate && npm run start:dev"

  postgres:
    image: postgres:15
    container_name: nest_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: narriva_server
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
